name: Update M3U8

on:
  schedule:
    - cron: '0 */5 * * *' # Jalan tiap 5 jam
  workflow_dispatch: # Biar bisa run manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install yt-dlp
        run: pip install yt-dlp
        
      - name: Generate M3U8
        run: |
          mkdir -p public
          while IFS='|' read -r name url; do
            yt-dlp -g "$url" > public/"$name".m3u8
          done < channels.txt
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
